apiVersion: apps/v1
kind: Deployment
metadata:
  name: yal-webapp
spec:
  selector:
    matchLabels:
      app: yal-webapp
  template:
    metadata:
      labels:
        app: yal-webapp
    spec:
      containers:
      - image: thenicebutcher/youranimelist:v0.2
        name: test-web
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: youranimelistdb
        - name: POSTGRES_USER
          value: lelouch
        - name: POSTGRES_PASSWORD
          value: pwd
        ports:
        - containerPort: 8080
